version: "3.3"

services:
  mysql5:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - /root/data/mysql/5.6:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 38080:8080
    links:
      - mysql5:db
